---
- name: "Apply sysctl changes"
  ansible.builtin.command:
    cmd: sysctl -p

- name: "Restart networking"
  ansible.builtin.service:
    name: systemd-networkd
    state: restarted

- name: "Save iptables rules"
  ansible.builtin.command:
    cmd: netfilter-persistent save
