---
- name: "Enable IP forwarding"
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes
  notify: Apply sysctl changes

- name: "Copy netplan configuration file"
  ansible.builtin.copy:
    src: /etc/ansible/roles/static_ip_config/files/network-config.yaml
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: '0644'

- name: "Apply netplan configuration"
  ansible.builtin.command:
    cmd: netplan apply
  notify: Restart networking
