---
- name: "Enable IP forwarding"
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#?net.ipv4.ip_forward'
    line: 'net.ipv4.ip_forward=1'
    state: present
    backrefs: yes
  notify: Apply sysctl changes

- name: "Ensure IP forwarding is enabled on boot"
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-ip-forward.conf
    content: "net.ipv4.ip_forward=1\n"
    owner: root
    group: root
    mode: '0644'
  notify: Apply sysctl changes

- name: "Force immediate execution of handlers"
  ansible.builtin.meta: flush_handlers
    
- name: "Install ISC DHCP Server"
  ansible.builtin.apt:
    name: isc-dhcp-server
    state: present
    update_cache: yes

- name: "Copy DHCP configuration file"
  ansible.builtin.copy:
    src: /etc/ansible/roles/isc-dhcp/files/dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart DHCP Server

- name: "Ensure DHCP service is enabled and running"
  ansible.builtin.service:
    name: isc-dhcp-server
    state: started
    enabled: yes
