name: Terraform Plan
on: [push]  # La pipeline si attiva su ogni push

jobs:
  terraform:
    runs-on: ubuntu-latest  # Usa un runner Ubuntu per eseguire i comandi

    steps:
      # Step 1: Checkout del codice (scarica il repository)
      - uses: actions/checkout@v2

      # Step 2: Inizializza Terraform
      - name: Terraform Init
        run: terraform init

      # Step 3: Esegui Terraform Plan per vedere le modifiche pianificate
      - name: Terraform Plan
        run: terraform plan
